services:
  - type: web
    name: virtualshop-api
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      # The database environment variables (SPRING_DATASOURCE_URL, 
      # SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD)
      # should now be managed from the Render dashboard. 